---
- hosts: web_server
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: "{{myjavapackforubuntu}}"
      state: present
    when: ansible_os_family=='Debian'

  - name: install java on RedHat nodes
    yum:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family=='RedHat'