---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: I want to install git, tree, wget by using same tasks
    apt:
      name: "{{item}}"
      state: absent
    loop: 
      - git
      - tree
      - wget
