---
- hosts: all
  become: yes
  tasks:
  - name: I want to install git, tree, wget by using same tasks
    apt:
      name: "{{item}}"
      state: present
    loop:
      - git
      - tree
      - wget
