---
- hosts: all
  become: yes
  tasks:
  - name: I want to isntall webserver when os family is debian
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver when os family is debian
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Redhat"