---
- hosts: web_server
  become: yes
  tasks:
  - name: I want to isntall webserver when os family is debian
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver when os family is debian
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: install httpd on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: start httpd on redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"


- hosts: ubuntu_server
  become: yes
  tasks:
  - name: I want to isntall git when os family is debian
    apt:
      name: git
      state: present
    when: ansible_os_family=="Debian"


- hosts: redhat_server
  become: yes
  tasks:
  - name: I want to isntall httpd when os family is debian
    apt:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"